### ISSUE TITLE
Unable to find subtab

### ISSUE THREAD

**Issue by RampedIndent** [Korchy/blender-timeme#3]
So i am trying to use this addon in blender 2.9.3. it says it is installed however i cant find the tab anywhere. I've tried restarting blender, opening a new file. It does not appear with searching the properties tab.
![image](https://user-images.githubusercontent.com/39007301/124220013-832bae80-db40-11eb-9a73-963886180744.png)
![image](https://user-images.githubusercontent.com/39007301/124219971-6b542a80-db40-11eb-838d-969834cd9a99.png)
![image](https://user-images.githubusercontent.com/39007301/124220099-ae160280-db40-11eb-8d70-9be789f1152d.png)

**Comment by Korchy** [comment]
There is the dev version of the add-on on GitHub. You can get the release version from links from here https://b3d.interplanety.org/en/blender-timeme/

**Comment by RampedIndent** [comment]
wow i didn't even see those there.
